### ISSUE TITLE
Refactor Go API for Secret Management with Nested Namespaces

### ISSUE THREAD

**Issue by bcncpp** [zenforcode/keyfort#42]
# Ticket: Refactor Go API for Secret Management with Nested Namespaces

### Objective
Refactor the existing Go-based API to implement a flexible secret management system that:

- Allows secrets to be set and retrieved
- Associates each secret with a **nested namespace path** (e.g., `prod/team1/app1`)
- Supports multiple pluggable storage backends:
  - In-memory storage (for development and tests)
  - FoundationDB (for production)
- Enforces request headers for access control and context

---

### Entity Model

```mermaid
erDiagram
    SECRET ||--|| NAMESPACE : belongs_to
    STORAGE_BACKEND ||--o{ SECRET : stores

    SECRET {
        string id
        string key
        string value
        string namespace_id
    }

    NAMESPACE {
        string id
        string path
        string parent_id
    }

    STORAGE_BACKEND {
        string id
        string type
        string config
    }
```

---

### API Design

- `POST /secrets`
  - **Headers**:
    - `Authorization: Bearer <token>`
    - `X-Body-Metadata: <json>`
  - **Body**:
    ```json
    {
      "key": "API_KEY",
      "value": "abc123",
      "namespace": "prod/team1"
    }
    ```

- `GET /secrets/:namespace/:key`
  - Retrieves the secret using the namespace path and key

> Namespaces can be dynamically created. They are hierarchical and support nesting.

---

### Storage Layer

- Define a common interface:

```go
type SecretStorage interface {
    SetSecret(namespacePath, key, value string) error
    GetSecret(namespacePath, key string) (string, error)
}
```

- Backends:
  - `MemoryStorage`: in-memory map, supports unit testing
  - `FoundationDBStorage`: uses FoundationDB directory layers to model nested namespaces

---

### Testing and Mocks

- ✅ Unit tests for `MemoryStorage`
- ✅ Mocks for `SecretStorage` using `testify/mock`
- ✅ Integration tests for FoundationDB using test containers or Docker Compose

---

### Docker Compose Setup

```yaml
version: '3.8'

services:
  app:
    build: .
    command: ./app
    ports:
      - "8080:8080"
    environment:
      - STORAGE_BACKEND=foundationdb
      - FDB_CLUSTER_FILE=/etc/fdb/fdb.cluster
    depends_on:
      - foundationdb
    volumes:
      - ./fdb.cluster:/etc/fdb/fdb.cluster

  foundationdb:
    image: foundationdb/foundationdb:7.1.27
    environment:
      - FDB_COORDINATOR=fdb
    ports:
      - "4500:4500"
    volumes:
      - foundationdb-data:/var/lib/foundationdb

volumes:
  foundationdb-data:
```

---

### Deliverables

- [ ] API endpoints to set and retrieve secrets
- [ ] Namespace model with support for nested paths
- [ ] `SecretStorage` interface
- [ ] `MemoryStorage` implementation with tests
- [ ] `FoundationDBStorage` implementation with integration tests
- [ ] Docker Compose for local testing
- [ ] Header validation for `Authorization` and `X-Body-Metadata`
- [ ] Example requests in documentation
- [ ] README updates with instructions and examples
- [ ] Unit tests.
